#!/bin/sh
show_help() {
    echo "conv <boo-code> [-o <output-file>]"
}
if [[ $# == 0 ]]; then
    show_help
else
    while [[ $# > 0 ]]; do
        case "$1" in
            -h)
                show_help
                exit 0
                ;;
            -o)
                OUTPUT_FILE=$2
                shift
                ;;
            *)
                INPUT_FILE=$1
                ;;
        esac
        shift
    done
    ruby preprocess.rb $INPUT_FILE > tmp
    if [[ $OUTPUT_FILE = "" ]]; then
        txl tmp translate.txl
    else
        txl tmp translate.txl > $OUTPUT_FILE
    fi
fi

