#!/bin/sh
show_help() {
    echo "conv <boo-code> [-o <output-file>]"
}

translate_file() {
    ruby preprocess.rb $1 > tmp
    if [[ $2 = "" ]]; then
        txl tmp translate.txl
    else
        txl tmp translate.txl > $2
    fi
}

if [[ $# == 0 ]]; then
    show_help
else
    while [[ $# > 0 ]]; do
        case "$1" in
            -h)
                show_help
                exit 0
                ;;
            -o)
                OUTPUT_FILE=$2
                shift
                ;;
            -R)
                INPUT_FOLDER=$2
                shift
                ;;
            *)
                INPUT_FILE=$1
                ;;
        esac
        shift
    done
    if [[ $INPUT_FOLDER = "" ]]; then
        translate_file $INPUT_FILE $OUTPUT_FILE
    else
        if [[ $OUTPUT_FILE = "" ]]; then
            OUTPUT_FILE="output"
        fi
        mkdir -p $OUTPUT_FILE
        IFS=$'\n'
        rm -f error.log
        for f in `find $INPUT_FOLDER -name *.boo`; do
            fname=${f#$INPUT_FOLDER'/'}
            echo $f
            mkdir -p $OUTPUT_FILE"/"${fname%/*}
            translate_file $f $OUTPUT_FILE"/"${fname%boo}"cs" 2>> error.log
            if [[ $? = 0 ]]; then
                echo "\033[0;32mOK\033[0m"
            else
                echo "\033[0;31mFailed\033[0m"
            fi
        done
    fi
fi

